### ISSUE TITLE
How to combine text file result?

### ISSUE THREAD

**Issue by kan1207** [logstash-plugins/logstash-codec-avro#17]
I have some scheduled batch jobs running automatically during the night and will show the results in separate .txt files. Is there anyway to grab the data from the .txt file and consolidate them to display in kibana? Any tools or reference .conf?

Here is the case:(Windows)

Job Code.txt

> job_id=0001,description=Ship data from server to elknode1
> job_id=0002,description=Ship data from server to elknode2
> job_id=0003,description=Ship data from server to elknode3
> job_id=0004,description=Ship data from server to elknode4

Job Status.txt

> job_id=0001,result=OK
> job_id=0002,result=Error: Msg...
> job_id=0003,result=OK
> job_id=0004,result=OK

Here is my very basic logstash.conf file I knew what should be written

> input{
> file{
> path => "C:/Job/*.txt"
> start_position => "beginning"
> }
> }
> filter{}
> output{
> elasticsearch { hosts => ["localhost:9200"] }
> stdout { codec => rubydebug } 
> }

How can I combine the two into one

Thanks

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
